services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${CONFIG}\nginx-config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    networks:
      - db_network

  mysql:
    image: mysql
    container_name: mysql
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'website_db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: '123'
    volumes:
      - ${CONFIG}\mysql-config:/var/lib/mysql
    networks:
      - db_network

  bot:
    container_name: discord_bot
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    build:
      context: ${CONFIG}\discord-bot
    volumes:
      - ${CONFIG}\discord-bot:/usr/src/app
    working_dir: /usr/src/app
    restart: unless-stopped
    command: [ "node", "src/index.js" ]

  muse:
    image: ghcr.io/museofficial/muse:pr-1256
    container_name: music_bot
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    restart: unless-stopped
    volumes:
      - ${CONFIG}\muse-config:/data
    environment:
      - DISCORD_TOKEN=${MUSE_TOKEN}
      - YOUTUBE_API_KEY=${YOUTUBE_KEY}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_SECRET}

  pythonapp:
    container_name: python_app
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    build:
      context: ${CONFIG}\pythonapp-config\Python-Projects
      dockerfile: dockerfile
    volumes:
      - ${CONFIG}\pythonapp-config:/app
    ports:
      - "8501:8501"
    restart: unless-stopped

  chatapp:
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    build:
      context: ${config}\chatapp-config
      dockerfile: dockerfile
    ports:
      - "9876:9876"
    container_name: chatapp
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: 123
      DB_NAME: chat_db
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    networks:
      - db_network
    restart: unless-stopped

  registry:
    image: registry:2
    container_name: registry
    ports:
      - "5000:5000"
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M
    volumes:
      - ${CONFIG}\registry:/var/lib/registry
      - ${CONFIG}\registry-config\config.yml:/etc/docker/registry/config.yml
    restart: unless-stopped

  registry-ui:
    image: joxit/docker-registry-ui:main
    container_name: registry-ui
    ports:
      - "5001:80"
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M
    environment:
      - REGISTRY_TITLE=Homelab Registry
      - REGISTRY_URL=https://reg.levimclean.tech
    depends_on:
      - registry
    restart: unless-stopped
networks:
  db_network:
    driver: bridge