services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${CONFIG}\nginx-config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    networks:
      - db_network

  mysql:
    image: mysql
    container_name: mysql
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'website_db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: '123'
    volumes:
      - ${CONFIG}\mysql-config:/var/lib/mysql
    networks:
      - db_network

  levibot:
    container_name: levibot
    build: ${CONFIG}\discord-bot
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    volumes:
      - ${CONFIG}\discord-bot:/usr/src/app
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=false

  muse:
    image: ghcr.io/museofficial/muse:pr-1256
    container_name: music_bot
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    restart: unless-stopped
    volumes:
      - ${CONFIG}\muse-config:/data
    environment:
      - DISCORD_TOKEN=${MUSE_TOKEN}
      - YOUTUBE_API_KEY=${YOUTUBE_KEY}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_SECRET}

  pythonapp:
    container_name: python_app
    build: ${CONFIG}\pythonapp-config\Python-Projects
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    volumes:
      - ${CONFIG}\pythonapp-config:/app
    ports:
      - "8501:8501"
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=false

  chatapp:
    build: ${CONFIG}\chatapp-config
    ports:
      - "9876:9876"
    container_name: chatapp
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: 123
      DB_NAME: chat_db
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    networks:
      - db_network
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=false

  pairdrop:
    container_name: pairdrop
    restart: unless-stopped
    image: lscr.io/linuxserver/pairdrop:latest
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - RATE_LIMIT=false 
    ports:
      - 6969:3000

networks:
  db_network:
    driver: bridge