services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${CONFIG}\nginx-config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    networks:
      - db_network

  mysql:
    image: mysql
    container_name: mysql
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'website_db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: '123'
    volumes:
      - ${CONFIG}\mysql-config:/var/lib/mysql
    networks:
      - db_network

  levibot:
    container_name: levibot
    build: ${CONFIG}\discord-bot
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    volumes:
      - ${CONFIG}\discord-bot:/usr/src/app
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=false

  muse:
    image: ghcr.io/museofficial/muse:pr-1256
    container_name: music_bot
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    restart: unless-stopped
    volumes:
      - ${CONFIG}\muse-config:/data
    environment:
      - DISCORD_TOKEN=${MUSE_TOKEN}
      - YOUTUBE_API_KEY=${YOUTUBE_KEY}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_SECRET}

  pairdrop:
    container_name: pairdrop
    restart: unless-stopped
    image: lscr.io/linuxserver/pairdrop:latest
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - RATE_LIMIT=false 
    ports:
      - 6969:3000

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    environment:
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - NODE_ENV=production
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=123
      - DB_SQLITE_VACUUM_ON_STARTUP=true
      - DB_SQLITE_POOL_SIZE=5
      - N8N_RUNNERS_ENABLED=true
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - N8N_GIT_NODE_DISABLE_BARE_REPOS=true
    volumes:
      - ${CONFIG}\n8n-config:/home/node/.n8n
    ports:
      - 5678:5678
    restart: unless-stopped
    networks:
      - db_network

  aig:
    build: ${CONFIG}\aig-config
    container_name: aig
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M
    environment:
      - BASE_URL=https://aig.levimclean.me
    ports:
      - "1255:1255"
    volumes:
      - ${CONFIG}\aig-config\images:/app/images
    restart: unless-stopped

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - TZ=${TZ}
      - GITEA__server__ROOT_URL=https://git.levimclean.me/
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    restart: unless-stopped
    volumes:
      - ${CONFIG}\gitea-config:/data
    networks:
      - db_network

# Not in use #
  # pythonapp:
  #   container_name: python_app
  #   build: ${CONFIG}\pythonapp-config\Python-Projects
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 256M
  #       reservations:
  #         memory: 128M
  #   volumes:
  #     - ${CONFIG}\pythonapp-config:/app
  #   ports:
  #     - "8501:8501"
  #   restart: unless-stopped
  #   labels:
  #     - com.centurylinklabs.watchtower.enable=false

  # chatapp:
  #   build: ${CONFIG}\chatapp-config
  #   ports:
  #     - "9876:9876"
  #   container_name: chatapp
  #   environment:
  #     DB_HOST: mysql
  #     DB_USER: root
  #     DB_PASS: 123
  #     DB_NAME: chat_db
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 128M
  #       reservations:
  #         memory: 64M
  #   networks:
  #     - db_network
  #   restart: unless-stopped
  #   labels:
  #     - com.centurylinklabs.watchtower.enable=false
  
  # yt-archiver:
  #   labels:
  #     - "com.centurylinklabs.watchtower.enable=false"
  #   build: ${CONFIG}\yt-archiver-config
  #   container_name: yt-archiver
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 512M
  #   environment:
  #     - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK}
  #   volumes:
  #     - ${VIDEOS}:/videos
  #     - ${CONFIG}\yt-archiver-config\cookies.txt:/app/cookies.txt
  #   ports:
  #     - 7654:7654
  #   restart: unless-stopped

networks:
  db_network:
    driver: bridge