services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    mem_limit: 256M
    environment:
      PUID: 1000
      PGID: 1000
      HOMEPAGE_ALLOWED_HOSTS: "*"
    ports:
      - 3000:3000
    volumes:
      - ${CONFIG}/homepage-config:/app/config
      - ${CONFIG}/homepage-config/images:/app/public/images # optional, for images 
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    ports:
      - "8082:80"
    mem_limit: 64M
    volumes:
      - ${MEDIA}:/srv/media
      - ${CONFIG}:/srv/config
      - /mnt/SSD/Yarr/Windows Games:/srv/yarr
      - ${CONFIG}/filebrowser-config:/config
      - ${CONFIG}/filebrowser-config:/database
    labels:
      - com.centurylinklabs.watchtower.enable=false
    restart: unless-stopped

  diskWake:
    container_name: diskWake
    image: diskwake:latest
    build: ${CONFIG}/diskwake-config
    mem_limit: 64M
    volumes:
      - "${MEDIA}:/mnt/externalhdd"
    labels:
      - com.centurylinklabs.watchtower.enable=false
    restart: unless-stopped

  glances:
    image: nicolargo/glances:latest
    container_name: glances
    pid: host
    uts: host
    mem_limit: 128M
    environment:
      - TZ=${TZ}
      - "GLANCES_OPT=-w"
    ports:
      - "61208:61208"
    volumes:
      - ${CONFIG}/glances-config:/glances/conf
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/os-release:/etc/os-release:ro
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    mem_limit: 128M
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}
  
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - SERVERPORT=51820
      - PEERS=5
      - ALLOWEDIPS=0.0.0.0/0
      - LOG_CONFS=true
    volumes:
      - ${CONFIG}/wireguard-config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    mem_limit: 128M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8001:8080
    environment:
      - TZ=${TZ}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_NOTIFICATION_URL=discord://8aK38AwQ_uUjWzm4DHzSxDOfZe6zBSZ571PCvNNEl1KK8tcd8miF70h8y6NtpVdGsZYm@1323419622921338891
      - WATCHTOWER_HTTP_API_METRICS=true
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_TOKEN}
      - DOCKER_API_VERSION=1.52
    restart: unless-stopped
    command: --schedule "0 0 4 * * *"

# Not in use #
  # freshrss:
  #   image: lscr.io/linuxserver/freshrss:latest
  #   container_name: freshrss
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 128M
  #       reservations:
  #         memory: 64M
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=${TZ}
  #   volumes:
  #     - ${CONFIG}/freshrss-config:/config
  #   ports:
  #     - "8088:80"
  #   restart: unless-stopped

  # rss-bridge:
  #   image: rssbridge/rss-bridge:latest
  #   container_name: rss-bridge
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 128M
  #       reservations:
  #         memory: 64M
  #   environment:
  #     - TZ=${TZ}
  #   ports:
  #     - "8089:80"
  #   restart: unless-stopped