services:
  mc:
    image: itzg/minecraft-server
    container_name: minecraft-server
    mem_limit: 6g
    environment:
      # Required
      EULA: "true"
      TZ: "America/Toronto"
      MEMORY: "6G"
      UID: 1000
      GID: 1000
      # CurseForge Shit
      TYPE: VANILLA
      # CF_API_KEY: ${CURSEFORGE_TOKEN}
      # CF_MODPACK_MANIFEST: /data/manifest.json
      # CF_SLUG: "custom"
      # Server Configuaration
      MOTD: |
        \u00A7k420 \u00A7r \u00A7eFUCKWITS SERVER UNITE (╯°□°)╯︵ ┻━┻ \u00A77\u00A7k420\u00A7r 
        \u00A7k420\u00A7r \u00A75MINECRAFT \u00A76SERVER \u00A79LETSGOOOOOOOO \u00A7r\u00A7k420
      ICON: ./icon.png
      LEVEL: vanillaWorld # Change if moving to modded server
      SERVER_NAME: FUCKWITS SERVER UNITE (╯°□°)╯︵ ┻━┻
      MAX_PLAYERS: 6
      ENABLE_WHITELIST: "true"
      WHITELIST: LeviM0323, Dheltaz, _ruasuar_
      RCON_PASSWORD: ${RCON_PASSWORD}
    ports:
      - "25565:25565"
      - "25575:25575"
    volumes:
      - ${CONFIG}/minecraft-config:/data
    stdin_open: true
    tty: true
    restart: unless-stopped