services:
  # Automated Media Server Containers #
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    # network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ}
    volumes:
      - ${CONFIG}\sonarr-config:/config
      - ${MEDIA}:/media
    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    # network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ}
    volumes:
      - ${CONFIG}\radarr-config:/config
      - ${MEDIA}:/media
    ports:
      - "7878:7878"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    environment:
      - PUID=13006
      - PGID=13000
      - UMASK=002
      - TZ=${TZ}
    volumes:
      - ${CONFIG}\prowlarr-config:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    # network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ}
    volumes:
      - ${MEDIA}:/media
      - ${CONFIG}\sabnzbd-config:/config
    ports:
      - "8081:8081"
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${CONFIG}\tautulli-config:/config
    ports:
      - 8181:8181
    restart: unless-stopped

  doplarr:
    image: lscr.io/linuxserver/doplarr:latest
    container_name: doplarr
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - DISCORD__TOKEN=${DOPLARR_TOKEN}
      - RADARR__API=${RADARR_TOKEN}
      - RADARR__URL=http://192.168.2.21:7878
      - SONARR__API=${SONARR_TOKEN}
      - SONARR__URL=http://192.168.2.21:8989
      - DISCORD__MAX_RESULTS=10 #optional
      - DISCORD__REQUESTED_MSG_STYLE=:plain #optional
      - PARTIAL_SEASONS=false #optional
      - LOG_LEVEL=:info #optional
    volumes:
      - ${CONFIG}\doplarr-config:/config
    restart: unless-stopped