services:
  grafana:
    image: grafana/grafana-enterprise
    mem_limit: 256M
    container_name: grafana
    volumes:
      - ${CONFIG}/grafana-config:/var/lib/grafana
    restart: unless-stopped
    ports:
      - '2233:3000'

  loki:
    image: grafana/loki:latest
    container_name: loki
    mem_limit: 256M
    ports:
      - "3100:3100"
    volumes:
      - ${CONFIG}/loki-config:/etc/loki
    command: -config.file=/etc/loki/loki.yml
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    mem_limit: 256M
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ${CONFIG}/promtail-config:/etc/promtail
      - /var/log:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/promtail.yml
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    mem_limit: 128M
    container_name: prometheus
    volumes:
      - ${CONFIG}/prometheus-config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: unless-stopped

  docker_stats_exporter:
    image: wywywywy/docker_stats_exporter:latest
    mem_limit: 128M
    container_name: docker_stats_exporter
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9487:9487"
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter:latest
    mem_limit: 64M
    container_name: node_exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs=/rootfs
      - --collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"
    ports:
      - "9100:9100"
    restart: unless-stopped

  mc-monitor:
    image: itzg/mc-monitor
    mem_limit: 64M
    container_name: mc-monitor
    command: export-for-prometheus
    ports:
      - 7754:8080
    environment:
      EXPORT_SERVERS: mc
      DEBUG: "true"
    restart: unless-stopped